#!/usr/bin/env python3
"""Re-embed a corrected DCF JSON into an already-built dashboard.

Dashboards inline the whole DCF as `const dcfData = {...}` so they open from
file:// without a server (see CLAUDE.md, Dashboard Data Format). Normally the
page is regenerated by `build_dashboard.py`, which needs the
`{TICKER}_DashboardSpec.json` the dashboard-generator agent writes.

When ONLY the DCF JSON changed -- as with the 2026-09-01 entry-price correction,
which touched no intrinsic value, projection or assumption -- rebuilding through
an agent is both unnecessary and expensive. 41 of the 55 corrected tickers
predate the DashboardSpec format and have no committed spec at all, so this is
the only way to refresh them without a re-research.

This swaps the embedded literal and nothing else. It does not re-render charts,
re-read the CSV, or touch layout: if the change needs any of that, rebuild
properly instead.

Usage:  reembed_dcf.py --check [TICKER...]
        reembed_dcf.py --apply [TICKER...]
"""

from __future__ import annotations

import argparse
import glob
import json
import os
import re
import sys
from typing import Any

ASSIGN = re.compile(r"(const|let|var)\s+dcfData\s*=\s*")


class NoEmbeddedDCFError(Exception):
    """The page carries no `const dcfData = {...}` literal."""


class NotStrictJSONError(Exception):
    """The embedded literal is JS (unquoted keys), not strict JSON."""


def _span(html: str) -> tuple[int, int]:
    """Byte span of the JSON object literal assigned to dcfData.

    Scans with a brace counter that ignores braces inside JSON strings, so a
    `"note": "a } brace"` value cannot terminate the literal early.
    """
    m = ASSIGN.search(html)
    if not m:
        raise NoEmbeddedDCFError("no `const dcfData =` assignment")
    start = html.find("{", m.end())
    if start < 0:
        raise NoEmbeddedDCFError("no object literal after the assignment")
    depth, i, in_str, esc = 0, start, False, False
    while i < len(html):
        ch = html[i]
        if in_str:
            if esc:
                esc = False
            elif ch == "\\":
                esc = True
            elif ch == '"':
                in_str = False
        elif ch == '"':
            in_str = True
        elif ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                return start, i + 1
        i += 1
    raise NoEmbeddedDCFError("unterminated object literal")


def extract(html: str) -> str:
    """The embedded JSON text."""
    start, end = _span(html)
    return html[start:end]


def parse_embedded(html: str) -> Any:
    """The embedded literal, parsed. Raises if it is JS rather than JSON."""
    try:
        return json.loads(extract(html))
    except json.JSONDecodeError as exc:
        raise NotStrictJSONError(str(exc)) from exc


def reembed(html: str, dcf: dict[str, Any]) -> str:
    """Return `html` with the embedded DCF replaced by `dcf`."""
    start, end = _span(html)
    return html[:start] + json.dumps(dcf, indent=2, ensure_ascii=False) + html[end:]


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--check", action="store_true")
    g.add_argument("--apply", action="store_true")
    ap.add_argument("tickers", nargs="*")
    args = ap.parse_args(argv)

    if args.tickers:
        paths = [f"research/{t}/Reports/{t}_DCF.json" for t in args.tickers]
    else:
        paths = sorted(glob.glob("research/*/Reports/*_DCF.json"))

    done, skipped = [], []
    for jpath in paths:
        ticker = os.path.basename(jpath).replace("_DCF.json", "")
        hpath = f"research/{ticker}/Reports/{ticker}_Dashboard.html"
        if not (os.path.exists(jpath) and os.path.exists(hpath)):
            continue
        with open(jpath) as fh:
            dcf = json.load(fh)
        with open(hpath) as fh:
            html = fh.read()
        try:
            if parse_embedded(html) == dcf:
                continue
        except (NoEmbeddedDCFError, NotStrictJSONError) as exc:
            skipped.append((ticker, str(exc)[:70]))
            continue
        done.append(ticker)
        if args.apply:
            with open(hpath, "w") as fh:
                fh.write(reembed(html, dcf))

    verb = "re-embedded" if args.apply else "would re-embed"
    print(f"{verb} {len(done)} dashboard(s)")
    for ticker in done:
        print(f"  {ticker}")
    if skipped:
        print(f"\nskipped {len(skipped)} (no embedded dcfData):")
        for ticker, why in skipped:
            print(f"  {ticker:<10} {why}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
